### ISSUE TITLE
"No notification" appears instead of an icon

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/mintsystem#120]
Instead of an icon, the text "No notification" appears. It's annoying because it's very large and takes too much place.

![Capture du 2020-07-09 21-09-32](https://user-images.githubusercontent.com/3955499/87081330-745e3480-c229-11ea-9f1a-399ea586064f.png)

**Comment by InfoLibre** [comment]
I seems I've got this message only when I upgrade from Linux Mint MATE 19.3 to 20, not with a new install of Linux Mint MATE 20.

**Comment by mtwebster** [comment]
I'm not really sure what program is sending that.

Can you provide the output from:
```
gsettings --schemadir /usr/share/glib-2.0/schemas list-relocatable-schemas | grep org.mate.panel.applet
and
dpkg --list | grep notif
and
gsettings list-recursively | grep indicator
```
Thanks

**Comment by InfoLibre** [comment]
![Capture du 2020-07-10 19-35-39](https://user-images.githubusercontent.com/3955499/87182612-c748f200-c2e4-11ea-8e40-f77731fcfd60.png)

![Capture du 2020-07-10 19-35-04](https://user-images.githubusercontent.com/3955499/87182636-cca63c80-c2e4-11ea-8cfd-07d41ebe9a74.png)

![Capture du 2020-07-10 19-36-36](https://user-images.githubusercontent.com/3955499/87182649-d29c1d80-c2e4-11ea-9cd4-71c38440f7fc.png)

**Comment by InfoLibre** [comment]
It's this applet that show the message :

![notification](https://user-images.githubusercontent.com/3955499/87217805-95b84100-c34d-11ea-88ff-0f70269fd932.png)

**Comment by clefebvre** [comment]
This needs to be reported upstream in MATE.

**Comment by InfoLibre** [comment]
I don't use MATE anymore. I'm using Cinnamon.
