### ISSUE TITLE
[FR] Add LibreOffice documents to templates in home dir of user

### ISSUE THREAD

**Issue by kacperpaczos** [linuxmint/mintsystem#134]
Add LibreOffice documents to templates in home dir of user

**Comment by clefebvre** [comment]
Added to roadmap. This will need to be localized properly (probably in Nemo).

**Comment by kacperpaczos** [comment]
@clefebvre,
Where can I locate the roadmap?

Consider using xdg-xubuntu-templates from: 
`git clone https://git.launchpad.net/xubuntu-default-settings`
It's a simple Python script.

How do you think it should be done in Linux Mint?
I could probably implement this feature...
