### ISSUE TITLE
[Feature Req] Update Firefox screenshot in the desktop installer slideshow

### ISSUE THREAD

**Issue by mrworldwide1** [linuxmint/mintsystem#137]
The image in installer slide show should be updated because for 3 years now Firefox redesigned its interface - pictures below. This is important to ensure Mint doesn't seem outdated, especially to new users who open up Firefox after installing the OS and see the inconsistency.

https://blog.mozilla.org/en/products/firefox/fresh-new-look-for-firefox/

**Current:**
![Screenshot from 2024-03-29 18-11-55](https://github.com/linuxmint/ubiquity/assets/66652566/ee91b0e2-4590-4159-bbac-56d087bcce5a)

**Expected:**
![image](https://github.com/linuxmint/ubiquity/assets/66652566/62e17b24-7790-4a60-9b47-6d827a7b6904)

**Comment by mrworldwide1** [comment]
The windows 7 and Internet Explorer screenshots are also outdated, per https://github.com/linuxmint/ubiquity/issues/71

**Comment by clefebvre** [comment]
Closing since this is tracked on ubiquity.
