### ISSUE TITLE
Remove cowsay dependency, if possible

### ISSUE THREAD

**Issue by theSeppi** [linuxmint/mintsystem#27]
I don't understand why mintsystem depends on the package cowsay...

For an experiment on the APT lock file,I needed a package to remove and install. I usually use cowsay because it seems so unimportant. However, it removed a bunch of system packages, too.

Using APT's log file, I managed to reinstall those packages, but I don't understand why this needed to happen. Is there any good reason for mintsystem depending on cowsay? If not, please remove it.

***
APT log:

    Start-Date: 2014-12-31  13:09:49
    Commandline: apt-get remove cowsay
    Remove: mint-artwork-gnome:amd64 (2.6.36), mint-meta-cinnamon:amd64 (2014.12.09), mint-meta-core:amd64 (2014.12.09), cowsay:amd64 (3.03+dfsg1-6), mint-artwork-common:amd64 (1.8.4), mintsystem:amd64 (7.9.7), ubuntu-system-adjustments:amd64 (2014.11.19)
    End-Date: 2014-12-31  13:10:13

PS: Also mint-meta-core depends on cowsay separately, additionally to mintsystem.

**Comment by monsta** [comment]
It's used for displaying fortunes in the terminal, see [this script](https://github.com/linuxmint/mintsystem/blob/master/usr/bin/mint-fortune).

**Comment by fbidu** [comment]
on a related matter, does `com.linuxmint.terminal show-fortunes` defaults to `false`?

**Comment by clefebvre** [comment]
yes

**Comment by dralley** [comment]
@clefebvre This issue can be closed since you fixed it here https://github.com/linuxmint/mintsystem/commit/8956b8a3fdc95e22d813924fb925ffda079805ea
