### ISSUE TITLE
Swap in a logical partition

### ISSUE THREAD

**Issue by Petrouchka** [linuxmint/mintsystem#33]
After installing Linux Mint 17.3 bêta, I saw that swap partition is in a logical partition, alone in an extended partition.
Putting the swap partition at the end of the disk is a good idea because it's easiest to move the swap partition after cloning by example. But why not only create a primary partition for swap ? It would be perfect.

**Comment by monsta** [comment]
Installer is here: https://github.com/linuxmint/ubiquity

**Comment by InfoLibre** [comment]
Thank you but how to make a bug report in https://github.com/linuxmint/ubiquity ? Bug report is inactivated.
