### ISSUE TITLE
Turn /usr/local/bin/apt into a wrapper for /usr/bin/apt

### ISSUE THREAD

**Issue by dralley** [linuxmint/mintsystem#38]
```/usr/local/bin/apt``` currently overrides ```/usr/bin/apt```, the system package provided by Debian/Ubuntu.  This is not a problem, per-se, except that it does not behave the same as the system package which can cause confusion when people are looking online for help, or when they expect it to behave as Debian/Ubuntu's "apt" does.

```/usr/local/bin/apt``` should be updated to provide a strict superset of the functionality of the system "apt" by wrapping the commands it provides.  This will make Mint's "apt" behavior consistent with that of Debian and Ubuntu where the two overlap.

**Comment by MichaelTunnell** [comment]
I think this is a great idea because it would allow the script to still be used when the tools don't overlap but keeps consistency of usability when related to other distros.

**Comment by dralley** [comment]
Thanks for reminding me - we did this a few weeks back!
