### ISSUE TITLE
Don't modify /etc/lsb-release it can breaks packages

### ISSUE THREAD

**Issue by zfil** [linuxmint/mintsystem#45]
Modifying /etc/lsb-release is a bad idea, as we are using packages from ubuntu, some package maintainers uses /etc/lsb-release instead of /etc/os-release to detect version and take decisions.

Therefore modifying it could lead to unpredictable results.

For instance `libvirt` package:

```
ifeq ($(shell dpkg --compare-versions "$(shell grep DISTRIB_RELEASE /etc/lsb-release | cut -d= -f2)" ge "14.04" && echo "yes"),yes)
	APPARMOR_REQ = -V'dist:Conflicts=apparmor (<< 2.8.95~2430-0ubuntu4)'
endif
ifeq ($(shell dpkg --compare-versions "$(shell grep DISTRIB_RELEASE /etc/lsb-release | cut -d= -f2)" ge "14.10" && echo "yes"),yes)
	APPARMOR_REQ = -V'dist:Conflicts=apparmor (<< 2.8.96~2652-0ubuntu1)'
endif
```

**Comment by zfil** [comment]
@clefebvre I know it is in the norm but the fact that some package maintainers don't respects it is a deal breaker for me ... Could you consider this ? Or a least comment on it :)

**Comment by clefebvre** [comment]
Hi,

There's no ideal solution for this.

These files are used both for cosmetic and compatibility reasons. The only way this works "properly" is by asking upstream developers to take Linux Mint in consideration.

Lately both /etc/os-release and /etc/lsb_release are showing Mint information (in Mint 18), and that's how it "should" be.

**Comment by zfil** [comment]
That's a poor decision IMHO ...
I can't see that package maintainers from the upstream distribution to take specifically Mint in account.
I've reverted using pure Ubuntu distribution as my teammates.
Anyway thanks for your answer.
