### ISSUE TITLE
Issues with "apt download".

### ISSUE THREAD

**Issue by nameless3** [linuxmint/mintsystem#49]
```
$ apt download python3
......
71 packages can be upgraded. Run 'apt list --upgradable' to see them.
download: you must specify at least one package to download
xargs: aptitude: exited with status 255; aborting
```

Doesn't download because python3 is already installed. Uninstalled (and upgradable) packages download without issue.
Relevant code: [(https://github.com/linuxmint/mintsystem/blob/master/usr/local/bin/apt#L112)](https://github.com/linuxmint/mintsystem/blob/master/usr/local/bin/apt#L112)

The help command isn't displayed either:

```
$ apt help download
Traceback (most recent call last):
  File "/usr/local/bin/apt", line 107, in <module>
    archive_name = argoptions.split()[0]
IndexError: list index out of range
```

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintsystem/commit/a60383c1b1e81f1cc7f7ad922974fb476235af71
