### ISSUE TITLE
Trash mystery...

### ISSUE THREAD

**Issue by markfilipak** [linuxmint/mintsystem#52]
I'm working on a Trash mystery and have encountered some bugs/flaws in Mint (or Gnome?).

It appears that Mint in general, and Nemo in particular may not conform with this:

> ```
> The FreeDesktop.org Trash specification
> Written by Mikhail Ramendik <mr@ramendik.ru>
> Content by David Faure <faure@kde.org>, Alexander Larsson <alexl@redhat.com> and others on the FreeDesktop.org mailing list
> Version 0.7
> ```

or may be imposing a non-compliant and unpublished method regarding Trash.

Also, it appears that MInt does not conform with 'https://www.freedesktop.org/wiki/Specifications/basedir-spec/', regarding required environmental variables, to wit:

```
mark@mark-Lenovo-V570 ~ $ echo $XDG_DATA_DIRS
/usr/share/cinnamon:/usr/share/gnome:/usr/local/share/:/usr/share/:/usr/share/mdm/
mark@mark-Lenovo-V570 ~ $ echo $XDG_CONFIG_DIRS
/etc/xdg/xdg-cinnamon:/etc/xdg
mark@mark-Lenovo-V570 ~ $ echo $XDG_DATA_HOME

mark@mark-Lenovo-V570 ~ $ echo $XDG_CACHE_HOME

mark@mark-Lenovo-V570 ~ $ echo $XDG_CONFIG_HOME

mark@mark-Lenovo-V570 ~ $
```

I've encountered these problems while working on the following Trash mystery.

Step #1: I ran this script:

```
#!/bin/bash

echo This is a test>~/.local/share/Trash/files/bash.txt;
(
echo [Trash Info];
echo Path=~/bash.txt;
echo DeletionDate=$(date "+%Y-%m-%d"T"%T")
)>~/.local/share/Trash/info/bash.txt.trashinfo
```

It successfully created an entity named 'bash.txt' in the Trash.

Step #2: I echoed "This is a test" to '~/nemo.txt', then deleted it via Nemo.

Step #3: I compared the 2 'trashinfo' files.

```
mark@mark-Lenovo-V570 ~/.local/share/Trash/info $ xxd bash.txt.trashinfo
00000000: 5b54 7261 7368 2049 6e66 6f5d 0a50 6174  [Trash Info].Pat
00000010: 683d 2f68 6f6d 652f 6d61 726b 2f62 6173  h=/home/mark/bas
00000020: 682e 7478 740a 4465 6c65 7469 6f6e 4461  h.txt.DeletionDa
00000030: 7465 3d32 3031 362d 3130 2d31 3254 3133  te=2016-10-12T13
00000040: 3a31 323a 3030 0a                        :12:00.
mark@mark-Lenovo-V570 ~/.local/share/Trash/info $ xxd nemo.txt.trashinfo
00000000: 5b54 7261 7368 2049 6e66 6f5d 0a50 6174  [Trash Info].Pat
00000010: 683d 2f68 6f6d 652f 6d61 726b 2f6e 656d  h=/home/mark/nem
00000020: 6f2e 7478 740a 4465 6c65 7469 6f6e 4461  o.txt.DeletionDa
00000030: 7465 3d32 3031 362d 3130 2d31 3254 3133  te=2016-10-12T13
00000040: 3a31 343a 3539 0a                        :14:59.
```

So far so good. But when I select the 2 files in the Trash utility and attempt to restore them (Restore Selected Items), 'nemo.txt' restores fine, but 'bash.txt' produces this error:

> Could not determine original location of "bash.txt"
> The item cannot be restored from trash

The properties and permissions of the 2 files are identical.

There must be something deficient about the 'bash.txt.trashinfo' file created by my script that prevents subsequently restoring 'bash.txt'.

What could it be?

**Comment by mtwebster** [comment]
Nemo (and most other programs that use gnome libraries) uses gvfs (https://wiki.gnome.org/Projects/gvfs) for handling trash, there's really nothing on our end involved with this - we open a virtual location (trash://) or move files to it.

It got me wondering anyhow - I followed your steps, reproduced the issue.  If you navigate to the trash folder in nemo, you'll notice there is no original location or deleted date in the view for the bash file.  The reason for that, I suspect, is that the file never existed anywhere prior to being in the trash folder - gvfs keeps metadata for all files and folders (that have been accessed).  What I'm pretty sure is happening is that there is no metadata regarding that file anywhere, so gvfs has no way of knowing where it should be restored to.

Fwiw, gvfs metadata is kept in ~/.local/share/gvfs-metadata, and there are a number of bin utilities that are prefixed by `gvfs-`.  Unfortunately, the metadata files aren't in a human-readable format.

I'm just curious, what is the purpose of this exercise?  I can't imagine this happening except deliberately in order to demonstrate this issue.

**Comment by markfilipak** [comment]
> Nemo (and most other programs that use gnome libraries) uses gvfs (https://wiki.gnome.org/Projects/gvfs) for handling trash, there's really nothing on our end involved with this - we open a virtual location (trash://) or move files to it.

Well, I'm not really sure whether it's a gvfs problem or a mintsystem problem... I suspect the later (as will be discussed below).

> It got me wondering anyhow

Don't ya love a good mystery?

> I followed your steps, reproduced the issue. If you navigate to the trash folder in nemo, you'll notice there is no original location or deleted date in the view for the bash file.

> The reason for that, I suspect, is that the file never existed anywhere prior to being in the trash folder - gvfs keeps metadata for all files and folders (that have been accessed). What I'm pretty sure is happening is that there is no metadata regarding that file anywhere, so gvfs has no way of knowing where it should be restored to.

I don't know what you mean by "in the view for the bash file". There's 'Path=/home/mark/bash.txt' in
'~/.local/share/Trash/info/bash.txt.trashinfo'. Isn't that sufficient? Or are you referring to something else that I don't know about?

> Fwiw, gvfs metadata is kept in ~/.local/share/gvfs-metadata, and there are a number of bin utilities that are prefixed by gvfs-. Unfortunately, the metadata files aren't in a human-readable format.

Aha! Perhaps the metadata to which you allude is the "non-compliant and unpublished method regarding Trash" to which I refer in my original post  -- I just knew there had to be something like that. Tell me, What's the point of having "Path=" in a '.trashinfo' file if gvfs is going to use metadata as the target of the restore?

> I'm just curious, what is the purpose of this exercise? I can't imagine this happening except deliberately in order to demonstrate this issue.

Oh, that's fine. My script is just to demonstrate this issue. The real script queries the user (i.e., zenity) for a file-or-directory name-fragment &/or path-fragment to search for. Then it makes a full-path global file list pipes it to grep for culling while doing a fixup (adding '/' to end of terminal directory names) and saves it in Trash. Then it opens that trashed file in Xed. (Note that the list of fragments found is prepended with a tip to the user to "Save As..." if the list is to be permanently saved.) By using Trash instead of '/tmp', there's no maintenance needed.

If the user doesn't "Save As..." and instead, leaves the file in Trash, there's no penalty. However, if the user remembers the file and says, "Oh, I needed to save that list", he/she can go to Trash and either open it in Xed once again, or (if I can overcome the metadata issue), the user can simply "Restore" the file and it will be 'restored' to his/her home directory.

Let me know if you want to see the real script. In the mean time, I'm going to experiment with 'gvfs-trash' in the script -- that is, pipe the processed path listing to ~ with a temporary name that uses the UTC to produce a unique name, then delete it with 'gvfs-trash', and then open the Trash copy in Xed. That approach will be a little more complicated (unique file name), but if it works, it will be worth it.
For Breaking News, stay tuned to this channel.

**Comment by markfilipak** [comment]
Okay! Success. I used 'gvfs-trash' to work around the problem. But it still bothers me that simply creating a valid '.trashinfo' file wasn't enough.

Oh, well. Here's my first bash script:
```
#!/bin/bash

saveT=$T;saveYmdHMSN=$YmdHMSN;saveIFS=$IFS;
T=$(zenity --entry --text="What \(file- folder- path-fragment\) do you want to find?\nExample: my/name is Joe" 2>/dev/null);
if (test "$T")
then
(
	YmdHMSN=$(date "+%Y%m%d%H%M%S%N");
	(
	echo Results of search for \"$T\";
	echo \(Tip: Use \'Save As...\' to permanently save this list\);
	echo;
	IFS=$(echo -en "\n\b");
	for N in $(find / 2>/dev/null|grep $T)
	do
		if (test -d $N)
		then echo "$N/";
		else echo "$N";
		fi;
	done;
	echo
	)>~/gfind-$YmdHMSN.txt && gvfs-trash ~/gfind-$YmdHMSN.txt && xed ~/.local/share/Trash/files/gfind-$YmdHMSN.txt
)
fi;
IFS=$saveIFS;T=$saveT;YmdHMSN=$saveYmdHMSN;
saveIFS=;saveT=;saveYmdHMSN=;
```
and it works in a menu launcher.

Of course, I had some help, but I do understand what every char is doing. I'm sure some chars that are legal in file & directory names will break it, but it will do for now. If this was javascript, I'd know how to escape the strings, but I don't know how to do that in bash. -- Cheers!
