### ISSUE TITLE
Missing activity status (hang during boot?)

### ISSUE THREAD

**Issue by markfilipak** [linuxmint/mintsystem#53]
Missing activity status (hang during boot?)

The boot process appears to hang with no status to the user.

After reading this:

'http://askubuntu.com/questions/435066/how-to-skip-boot-time-fsck-check-preferably-by-editing-grub-menu-entry'
"...the default should be to check once every 30 boots." – terdonhttp://askubuntu.com/users/85695/terdon Mar 19 '14 at 0:29

I believe the situation may be that an extended file system check is in progress...

But the user is not informed of it <-- This is a design flaw that should be fixed.

Impact: I have been turning my system off, then back on and taking the default boot option in grub. I understand now that doing so is not wise. But what choice do I have when the boot appears to hang?

**Comment by clefebvre** [comment]
Sorry, this isn't related to mintsystem.
