### ISSUE TITLE
Apt doesn't search well

### ISSUE THREAD

**Issue by Gemmu** [linuxmint/mintsystem#58]
Imho the search for apt should be returned back from aptitude to /usr/bin/apt.

For an example: 
```bash
$ /usr/local/bin/apt search "remote desktop client" | wc -l
1173
$ /usr/bin/apt  search "remote desktop client" | wc -l
35
```
Where the latter gives much better results, where as the previous (`aptitude`) ignores the quotes and searches for each word separately.

Using apt instead of aptitude for searching would also give the same results as the searches on Ubuntu's apt, which would be better when, for an example, one is following online guides and tutorials.

Should anyone want especially the search results from aptitude, aptitude itself could be used. Now this is just confusing.

**Comment by clefebvre** [comment]
This is by design: https://github.com/linuxmint/mintsystem/commit/0a7077a18b8a906135c02da19307bd34fc8c70e1
