### ISSUE TITLE
Steam client from steam website not work out the box.

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/mintsystem#60]
Hi
I know that i can install steam from software manager but i should can install steam from official website, normally, like on windows (It is important for new users).
I have laptop with Radeon HD 8550M. I have error on linux kernel 4.4.x and 4.8.x.

Running Steam on linuxmint 18.1 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(0)
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast

When i installed steam from software manager all was ok but why steam not work when i install official client from steam webiste?

**Comment by calexil** [comment]
first, install steam from the repo's

sudo apt remove purge steam*

sudo apt install steam:i386

than you need to do this:

https://www.reddit.com/r/linuxmint/comments/4rx1ft/steam_update_broke_steam_itself/d54wcf7/

**Comment by pyroxar** [comment]
I understand but my opinion this is wrong feature that in the mint i can't install steam client normally from website. Valve to make available download client form their website so i think that steam client should work out the box.

**Comment by pyroxar** [comment]
I think I found a way to fix that.
http://www.omgubuntu.co.uk/2017/06/steam-now-available-flatpak
