### ISSUE TITLE
minsystem apt-update fails with "invalid syntax" when python set to python3

### ISSUE THREAD

**Issue by jimbolaya** [linuxmint/mintsystem#61]
Due to other packages requiring python3 to be the default python, I changed /usr/bin/python to point to python3.

Error goes away when I set python to point to python2.

Preparing to unpack .../skypeforlinux_5.2.0.1_amd64.deb ...
Unpacking skypeforlinux (5.2.0.1) over (5.1.0.1) ...
Processing triggers for mintsystem (7.9.3+1) ...
  File "/usr/lib/linuxmint/mintSystem/mint-adjust.py", line 128
    except Exception, detail:
                    ^
SyntaxError: invalid syntax
dpkg: error processing package mintsystem (--unpack):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for mime-support (3.54ubuntu1.1) ...

**Comment by clefebvre** [comment]
Shebangs are defined now and migration done to python3.
