### ISSUE TITLE
Bash completion doesn't work with all apt commands

### ISSUE THREAD

**Issue by AvantR** [linuxmint/mintsystem#73]
Bash completion doesn't work with all apt commands. 

In my testing with LM 19, "full-upgrade" and "list" didn't autocomplete and possibly others as well.

**Comment by clefebvre** [comment]
https://github.com/linuxmint/mintsystem/commit/e48988e484348abc1bf72ad9ea2ce405adfe06f6

**Comment by ckristi** [comment]
Hi Clement,

The "apt li<tab>" now autocompletes to "apt list", however, if I try "apt list --upgra<tab>" it does not autocomplete to "apt list --upgradable". Would it be possible for this to be fixed as well? I really got used to it from my *ubuntu era.

Thank you,
Cristi
