### ISSUE TITLE
/etc/rc.local unavailable

### ISSUE THREAD

**Issue by ehtron** [linuxmint/mintsystem#74]
Hi :)
beta LM19 cinnamon 64 full level update
the file
/etc/rc.local is unavailable.
the systemd service is available and working.. 
after create the /etc/rc.local file, the rc.local startup works ... 
regards ehtron

**Comment by xenopeek** [comment]
Final release is already done. /etc/rc.local is a file the user can create if they need it. It needs to be executable for systemd to load it during late boot.
