### ISSUE TITLE
In Mint 19, my /etc/.bash_aliases no longer works

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/mintsystem#76]
`~/.bash_aliases` does still work, though (and the contents of '/etc/.bash_aliases' works if, and only if, I copy that content into `~/.bash_aliases`).

**Comment by gm10** [comment]
Was that ever set up like this by default? 
 
You'd have to either run it from `/etc/bash.bashrc` or $include it in `~/.bashrc` or `~/.bash_aliases`

**Comment by CottonEaster** [comment]
> Was that ever set up like this by default?

Perhaps not.
