### ISSUE TITLE
apt argument order

### ISSUE THREAD

**Issue by gm10** [linuxmint/mintsystem#77]
One of the error messages from binary apt:

E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

That command works fine with binary apt, but it won't work on Mint because the apt script currently cannot handle the reversed argument order, it is hardcoded to look for the command only in the first argument:

https://github.com/linuxmint/mintsystem/blob/master/usr/local/bin/apt#L80

Suggest to instead check all arguments for a known command, use the rest as options.

**Comment by kj800x** [comment]
I just ran into this too.

As a temporary workaround switching the argument order will work (`apt install --fix-broken`)

Mint 19.2: https://termbin.com/qt67

**Comment by gm10** [comment]
Feel free to use my PPA, it fixes this and many other bugs: https://launchpad.net/~gm10/+archive/ubuntu/linuxmint-tools

**Comment by ledenis** [comment]
Why is it closed?

The order still seems to be hardcoded to look for the command only in the first argument?

https://github.com/linuxmint/mintsystem/blob/master/usr/local/bin/apt#L64
