### ISSUE TITLE
Eject with WD My Passport Ultra external hard disk

### ISSUE THREAD

**Issue by BillDietrich** [linuxmint/mintsystem#87]
I have a WD My Passport Ultra external hard drive.  When I plug
it in to the PC, immediately a read-only "WD Unlocker"
device/drive is mounted (this is normal, it is used under
Windows or Mac to provide an app to decrypt and mount the real drive).
But then if I umount that drive and try to eject it, eject gives
an error.  I get the same error (via a dialog) if I use nemo to
eject the drive.

I'm using latest Mint 19 Cinnamon.

    [Plug in the drive]
    
    $ df
    Filesystem             1K-blocks      Used Available Use% Mounted on
    ...
    /dev/sr1                   13212     13212         0 100% /media/user1/WD Unlocker15
    
    $ mount
    ...
    /dev/sr1 on /media/user1/WD Unlocker15 type udf (ro,nosuid,nodev,relatime,uid=1000,gid=1000,iocharset=utf8,uhelper=udisks2)
    
    $ umount /dev/sr1
    $
    
    [Drive no longer appears in mount or df]
    
    $ eject -v /dev/sr1
    eject: device name is `/dev/sr1'
    eject: expanded name is `/dev/sr1'
    eject: `/dev/sr1' is not mounted
    eject: `/dev/sr1' is not a mount point
    eject: `/dev/sr1' is not a multipartition device
    eject: trying to eject `/dev/sr1' using CD-ROM eject command
    eject: CD-ROM eject command failed
    eject: trying to eject `/dev/sr1' using SCSI commands
    eject: SCSI eject failed
    eject: trying to eject `/dev/sr1' using floppy eject command
    eject: floppy eject command failed
    eject: trying to eject `/dev/sr1' using tape offline command
    eject: tape offline command failed
    eject: unable to eject, last error: Invalid argument
    
    $ eject -v /dev/nosuchdevice
    eject: device name is `/dev/nosuchdevice'
    eject: unable to find or open device for: `/dev/nosuchdevice'
    
    $ eject -h
    Eject version 2.1.5 by Jeff Tranter (tranter@pobox.com)
    ...

**Comment by clefebvre** [comment]
This is upstream from us and off-topic here (not related to mintsystem).

**Comment by BillDietrich** [comment]
I'm a n00b.  Please tell me the right place to file it.  Somewhere in Ubuntu or Debian ?
